.PHONY: clean all cleanall corelib

CC = avr-gcc
CXX = avr-g++
CXXFLAGS = -D__STDC_LIMIT_MACROS
LDFLAGS = 

all: corelib

corelib:
# REAL STUFF HERE

clean:
	rm -f *.o
	rm -f ../corelib.a

cleanall: clean
